// <auto-generated />
using System;
using MeetingRoomBooking.Infrastructure.MeetingRoomContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MeetingRoomBooking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620120000_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MeetingRoomBooking.Domain.Entities.RefreshToken", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Token").IsRequired().HasColumnType("text");
                b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime?>("RevokedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("RefreshTokens");
            });

            modelBuilder.Entity("MeetingRoomBooking.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("MeetingRoomBooking.Domain.Entities.User", "User").WithMany("RefreshTokens").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
        }
    }
}
